name: Build and create artifact
on: push
jobs:
  build:
    name: Build on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.8"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm64
      - uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
